/home/ubuntu/.pm2/logs/wgs-backend-out.log /home/ubuntu/.pm2/logs/wgs-backend-error.log {
    su ubuntu ubuntu
    size 2M
    rotate 5
    maxage 14
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
}
/var/log/wgs-security/nginx-access.log {
    size 2M
    rotate 5
    maxage 14
    missingok
    notifempty
    compress
    delaycompress
    create 0640 www-data adm
    sharedscripts
    postrotate
        /usr/sbin/nginx -s reopen >/dev/null 2>&1 || true
    endscript
}
